services:
  frontend:
    image: node:23-alpine
    restart: unless-stopped
    volumes:
      - '.:/app'
    ports:
      - '5173:5173'
    environment:
      - NODE_ENV=development
    command: ['npm', 'run', 'dev']
    env_file:
      - .env
    working_dir: /app
    networks:
      - caddie_network

networks:
  caddie_network:
    external: true
      #name: caddie_network