services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/app/prod/Dockerfile
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - caddie_network

networks:
  caddie_network:
    external: true
